name: Milestone Due Date

on:
  issues:
    types: [milestoned]

jobs:
  print_due_date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get milestone due date
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}
          MILESTONE_NUMBER=${{ github.event.issue.milestone.number }}

          MILESTONE_DATA=$(gh api repos/$REPO/milestones/$MILESTONE_NUMBER)

          DUE_DATE=$(echo $MILESTONE_DATA | jq -r '.due_on')

          if [ "$DUE_DATE" != "null" ]; then
            echo "Milestone due date for issue $ISSUE_NUMBER is $DUE_DATE"
          else
            echo "No due date set for milestone of issue $ISSUE_NUMBER"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
